version: "3.9"

services:
  # user service START
  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    depends_on:
      - postgres-users
      - kafka-cluster-1 
      - kafka-cluster-2
      - kafka-cluster-3
    ports:
      - "2000:2000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PostgresConnectionString=${USER_DB_CONNECTION}
      - Kafka__BootstrapServers=${KAFKA_BROKER}

  postgres-users:
    container_name: postgres-users
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_USERS_DB}
      POSTGRES_USER: ${POSTGRES_USERS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_USERS_PASSWORD}
    volumes:
      - postgres-users_data:/var/lib/postgresql/data
  # user service END
  
  # tweets service START
  tweetservice:
    build:
      context: ./TweetService
      dockerfile: Dockerfile
    depends_on:
      - postgres-tweets
    ports:
      - "2001:2001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PostgresConnectionString=${TWEET_DB_CONNECTION}
    
  postgres-tweets:
    container_name: postgres-tweets
    image: postgres:17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_TWEETS_DB}
      POSTGRES_USER: ${POSTGRES_TWEETS_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TWEETS_PASSWORD}
    volumes:
      - postgres-tweets_data:/var/lib/postgresql/data
  # tweets service FINISH
  
  # notification service START
  notificationsservice:
    build:
      context: ./NotificationsService
      dockerfile: Dockerfile
    depends_on:
      - mongo-notifications
      - kafka-cluster-1
      - kafka-cluster-2
      - kafka-cluster-3
    ports:
      - "2002:2002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=${NOTIFICATIONS_DB_CONNECTION}
      - KafkaSettings__BootstrapServers=${KAFKA_BROKER}
  
  mongo-notifications:
    image: mongo:6.0
    container_name: mongo-notifications
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_NOTIFICATIONS_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_NOTIFICATIONS_PASSWORD}
    volumes:
      - mongo-notifications_data:/data/db
  # notification service FINISH
  
  # discussion service START
  discussionservice:
    build:
      context: ./DiscussionService
      dockerfile: Dockerfile
    depends_on:
      - mongo-discussion
      - redis
    ports:
      - "2003:2003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=${DISCUSSION_DB_CONNECTION}
      - RedisServerAddress=redis:6379
  
  mongo-discussion:
    image: mongo:6.0
    container_name: mongo-discussion
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DISCUSSION_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DISCUSSION_PASSWORD}
    volumes:
      - mongo-discussion_data:/data/db
        
  redis:
    image: redis:8.0
    container_name: redis-discussion
    ports:
      - "6379:6379"
    volumes:
      - redis-discussion_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
  # discussion service FINISH
  
  # kafka clusters START
  zookeeper-cluster:
    container_name: zookeeper-cluster
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181 
  
  kafka-cluster-1:
    container_name: kafka-cluster-1
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper-cluster
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-cluster:2181 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-cluster-1:9092,PLAINTEXT_INTERNAL://kafka-cluster-1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1 # Минимальное количество синхронизированных реплик
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true" # Автоматическое создание топиков
    volumes:
      - kafka-cluster-1_data:/var/lib/kafka/data 

  kafka-cluster-2:
    container_name: kafka-cluster-2
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper-cluster
    ports:
      - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 2 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-cluster:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-cluster-2:9092,PLAINTEXT_INTERNAL://kafka-cluster-2:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-cluster-2_data:/var/lib/kafka/data 

  kafka-cluster-3:
    container_name: kafka-cluster-3
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper-cluster
    ports:
      - "9094:9092" 
    environment:
      KAFKA_BROKER_ID: 3 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-cluster:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-cluster-3:9092,PLAINTEXT_INTERNAL://kafka-cluster-3:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-cluster-3_data:/var/lib/kafka/data 
  # kafka clusters FINISH
  
  

volumes:
  postgres-users_data:
  postgres-tweets_data:
  mongo-notifications_data:
  mongo-discussion_data:
  redis-discussion_data:
  kafka-cluster-1_data: 
  kafka-cluster-2_data: 
  kafka-cluster-3_data: 